# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.12.0
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: Odoo Accounting Taxe and Fiscal Features
repo_name: account-fiscal-rule
repo_slug: account-fiscal-rule
repo_website: https://github.com/OCA/account-fiscal-rule
travis_apt_packages: []
travis_apt_sources: []

