# -*- coding: utf-8 -*-
# Copyright (C) 2014-Today GRAP (http://www.grap.coop)
# @author: Sylvain LE GAL (https://twitter.com/legalsylvain)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

- !record {model: product.template, id: product_template_1}:
    name: Demo Product With Fiscal Classification
    company_id: base.main_company
    categ_id: product.product_category_all
    type: service
    standard_price: 20.0
    list_price: 30.0
    fiscal_classification_id: fiscal_classification_1
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
