[project]
name = "odoo-addons-oca-account-fiscal-rule"
version = "19.0.20260901.0"
dependencies = [
    "odoo-addon-account_fiscal_position_partner_type==19.0.*",
    "odoo-addon-account_fiscal_position_vies_warning==19.0.*",
    "odoo-addon-product_refund_account==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
